### ISSUE TITLE
Triggers for farmer and policy makers actions

### ISSUE THREAD

**Issue by baudouindeparcevaux** [undpindia/Data4Policy#3]
Hello everyone, 
Our group has 3 questions about the event that should urge people to interact with the system.

Firstly, we know that policy makers should be able to identify well and poorly performing farmers. Should it be whenever they want ? (so even when farmers haven't finished their harvest) Or should it be once a year, semester,... ?

Likewise, should farmers be able to release production data whenever they want or on regular times (every month, semester,...) ?

Finally, for help request, is it the farmer that autonomously asks for it ? Or the system that identified that he was badly performing ? (independantly of the policy maker identification of poorly performing farmers)

**Comment by parvathykrishnank** [comment]
- The positive and negative deviance I think should be based on long-term trends and hence once a year would be good. But this is also based on the frequency and granularity of the data that you use. For example, some datasets might be updating every day (like weather) whereas others like soil parameters may be changing not as often. So the analysis should consider this. 
- Regarding farmer sharing their data, it is important that they share production and other data of interest as often as regularly as possible. Ideally throughout the cropping season.
- First policy maker can identify poorly performing farms and then understand why they are performing not as well as their peers, then provide targeted advisory.
