### ISSUE TITLE
What are the "incentives" ?

### ISSUE THREAD

**Issue by baudouindeparcevaux** [undpindia/Data4Policy#5]
Hello everyone,
Our group has 2 questions about the incentives the policy makers can grant to to farmers.

-Is this a financial support ?

-If it is the case, should it be handled by the system ? Or is it just supposed to warn the farmer, so that some kind of administrative procedure can be led to receive the cash ?

**Comment by parvathykrishnank** [comment]
Hello,

For this assignment, we did not include any data regarding the incentives to farmers. But you could recommend innovative systems like e-vouchers or subsidies based on the analysis that you do.
